# Generated by Django 5.1.4 on 2025-03-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0002_delete_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Department of Business", "Department of Business"),
                            (
                                "Department of Computer Science",
                                "Department of Computer Science",
                            ),
                            ("Department of Biology", "Department of Biology"),
                        ],
                        max_length=100,
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
