# Generated by Django 5.1.4 on 2025-03-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accession_no", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=100)),
                ("title", models.TextField()),
                ("author", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=30)),
            ],
        ),
    ]
