# Generated by Django 5.1.4 on 2025-03-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_book"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
