# Generated by Django 5.2 on 2025-04-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_review"),
        ("importcsv", "0002_alter_book_isbn"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review_text",
            new_name="comment",
        ),
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-04-11 00:00:00"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="importcsv.book",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
