# Generated by Django 5.2 on 2025-04-12 08:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_borrowrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrecord",
            name="borrow_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="borrowrecord",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrowrecord",
            name="borrow_id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=100, unique=True
            ),
        ),
    ]
