# Generated by Django 5.2 on 2025-04-14 05:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_borrowrecord_borrow_id_appuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=12, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Department of Business", "Department of Business"),
                            (
                                "Department of Computer Science",
                                "Department of Computer Science",
                            ),
                            ("Department of Biology", "Department of Biology"),
                        ],
                        max_length=100,
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="borrowrecord",
            name="borrow_id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.user",
            ),
        ),
        migrations.DeleteModel(
            name="AppUser",
        ),
    ]
