# Generated by Django 5.1.4 on 2025-03-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importcsv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=50),
        ),
    ]
